CREATE TYPE "public"."account_status" AS ENUM('active', 'suspended', 'deleted');--> statement-breakpoint
CREATE TYPE "public"."association_status" AS ENUM('pending', 'approved', 'suspended');--> statement-breakpoint
CREATE TYPE "public"."contact_method" AS ENUM('call', 'sms', 'whatsapp');--> statement-breakpoint
CREATE TYPE "public"."gender" AS ENUM('male', 'female');--> statement-breakpoint
CREATE TYPE "public"."initiative_status" AS ENUM('active', 'completed', 'upcoming');--> statement-breakpoint
CREATE TYPE "public"."mobility" AS ENUM('yes', 'hard', 'no');--> statement-breakpoint
CREATE TYPE "public"."need_status" AS ENUM('new', 'review', 'processing', 'responded', 'withdrawn', 'closed');--> statement-breakpoint
CREATE TYPE "public"."place_kind" AS ENUM('city', 'town', 'suburb', 'village', 'hamlet');--> statement-breakpoint
CREATE TYPE "public"."priority" AS ENUM('high', 'medium', 'low');--> statement-breakpoint
CREATE TYPE "public"."need_recurrence" AS ENUM('once', 'recurring');--> statement-breakpoint
CREATE TYPE "public"."need_since" AS ENUM('under_month', 'one_to_three', 'over_three', 'years');--> statement-breakpoint
CREATE TYPE "public"."urgency" AS ENUM('days', 'weeks', 'none');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('beneficiary', 'association', 'admin');--> statement-breakpoint
CREATE TABLE "association_categories" (
	"association_id" uuid NOT NULL,
	"category_id" smallint NOT NULL,
	CONSTRAINT "association_categories_association_id_category_id_pk" PRIMARY KEY("association_id","category_id")
);
--> statement-breakpoint
CREATE TABLE "association_coverage" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "association_coverage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"association_id" uuid NOT NULL,
	"governorate" text NOT NULL,
	"city" text
);
--> statement-breakpoint
CREATE TABLE "association_members" (
	"user_id" uuid NOT NULL,
	"association_id" uuid NOT NULL,
	"is_owner" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "association_members_user_id_association_id_pk" PRIMARY KEY("user_id","association_id")
);
--> statement-breakpoint
CREATE TABLE "associations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"initial" varchar(4) NOT NULL,
	"place" text NOT NULL,
	"governorate" text NOT NULL,
	"scope" text NOT NULL,
	"status" "association_status" DEFAULT 'pending' NOT NULL,
	"approved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "associations_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"actor_id" uuid,
	"action" text NOT NULL,
	"entity" text NOT NULL,
	"entity_id" text,
	"meta" jsonb,
	"at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "beneficiary_profiles" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"phone" varchar(16),
	"phone_verified" boolean DEFAULT false NOT NULL,
	"region" text,
	"city" text,
	"place_id" integer,
	"birth_year" smallint,
	"gender" "gender",
	"contact_method" "contact_method" DEFAULT 'call' NOT NULL,
	"completed_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "consents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"document_id" integer NOT NULL,
	"accepted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ip" varchar(64),
	"user_agent" text
);
--> statement-breakpoint
CREATE TABLE "initiatives" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"association_id" uuid NOT NULL,
	"city" text NOT NULL,
	"category_id" smallint NOT NULL,
	"status" "initiative_status" NOT NULL,
	"status_label" text NOT NULL,
	"started_at" text NOT NULL,
	"progress" smallint DEFAULT 0 NOT NULL,
	"beneficiaries" integer DEFAULT 0 NOT NULL,
	"target" integer DEFAULT 0 NOT NULL,
	"places" smallint DEFAULT 0 NOT NULL,
	CONSTRAINT "initiatives_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "legal_documents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "legal_documents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"doc_key" text NOT NULL,
	"title" text NOT NULL,
	"version" text NOT NULL,
	"published_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "need_categories" (
	"id" smallint PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "need_categories_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "need_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"need_id" uuid NOT NULL,
	"status" "need_status" NOT NULL,
	"title" text NOT NULL,
	"note" text,
	"actor_id" uuid,
	"at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "need_subcategories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "need_subcategories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"category_id" smallint NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "needs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reference" text NOT NULL,
	"beneficiary_id" uuid,
	"anonymized_at" timestamp with time zone,
	"category_id" smallint NOT NULL,
	"subcategory_id" integer,
	"region" text NOT NULL,
	"city" text NOT NULL,
	"place_id" integer,
	"since" "need_since" NOT NULL,
	"recurrence" "need_recurrence" NOT NULL,
	"mobility" "mobility" NOT NULL,
	"urgency" "urgency" NOT NULL,
	"followed_by_provider" boolean NOT NULL,
	"description" text NOT NULL,
	"contact_method" "contact_method" NOT NULL,
	"contact_time" text NOT NULL,
	"status" "need_status" DEFAULT 'review' NOT NULL,
	"priority" "priority",
	"assigned_association_id" uuid,
	"submitted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"closed_at" timestamp with time zone,
	CONSTRAINT "needs_reference_unique" UNIQUE("reference")
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"need_id" uuid,
	"read_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "phone_verifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"phone" varchar(16) NOT NULL,
	"code_hash" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"consumed_at" timestamp with time zone,
	"attempts" smallint DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "places" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "places_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"kind" "place_kind" NOT NULL,
	"governorate" text NOT NULL,
	"region" text NOT NULL,
	"lat" text,
	"lon" text
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_agent" text,
	"ip" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"role" "user_role" DEFAULT 'beneficiary' NOT NULL,
	"name" text NOT NULL,
	"status" "account_status" DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "association_categories" ADD CONSTRAINT "association_categories_association_id_associations_id_fk" FOREIGN KEY ("association_id") REFERENCES "public"."associations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "association_categories" ADD CONSTRAINT "association_categories_category_id_need_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."need_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "association_coverage" ADD CONSTRAINT "association_coverage_association_id_associations_id_fk" FOREIGN KEY ("association_id") REFERENCES "public"."associations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "association_members" ADD CONSTRAINT "association_members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "association_members" ADD CONSTRAINT "association_members_association_id_associations_id_fk" FOREIGN KEY ("association_id") REFERENCES "public"."associations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "beneficiary_profiles" ADD CONSTRAINT "beneficiary_profiles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "beneficiary_profiles" ADD CONSTRAINT "beneficiary_profiles_place_id_places_id_fk" FOREIGN KEY ("place_id") REFERENCES "public"."places"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consents" ADD CONSTRAINT "consents_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consents" ADD CONSTRAINT "consents_document_id_legal_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."legal_documents"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "initiatives" ADD CONSTRAINT "initiatives_association_id_associations_id_fk" FOREIGN KEY ("association_id") REFERENCES "public"."associations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "initiatives" ADD CONSTRAINT "initiatives_category_id_need_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."need_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "need_events" ADD CONSTRAINT "need_events_need_id_needs_id_fk" FOREIGN KEY ("need_id") REFERENCES "public"."needs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "need_events" ADD CONSTRAINT "need_events_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "need_subcategories" ADD CONSTRAINT "need_subcategories_category_id_need_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."need_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "needs" ADD CONSTRAINT "needs_beneficiary_id_users_id_fk" FOREIGN KEY ("beneficiary_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "needs" ADD CONSTRAINT "needs_category_id_need_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."need_categories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "needs" ADD CONSTRAINT "needs_subcategory_id_need_subcategories_id_fk" FOREIGN KEY ("subcategory_id") REFERENCES "public"."need_subcategories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "needs" ADD CONSTRAINT "needs_place_id_places_id_fk" FOREIGN KEY ("place_id") REFERENCES "public"."places"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "needs" ADD CONSTRAINT "needs_assigned_association_id_associations_id_fk" FOREIGN KEY ("assigned_association_id") REFERENCES "public"."associations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_need_id_needs_id_fk" FOREIGN KEY ("need_id") REFERENCES "public"."needs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "phone_verifications" ADD CONSTRAINT "phone_verifications_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "association_coverage_idx" ON "association_coverage" USING btree ("governorate","city");--> statement-breakpoint
CREATE INDEX "audit_log_entity_idx" ON "audit_log" USING btree ("entity","entity_id","at");--> statement-breakpoint
CREATE INDEX "consents_user_idx" ON "consents" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "legal_documents_key" ON "legal_documents" USING btree ("doc_key","version");--> statement-breakpoint
CREATE INDEX "need_events_need_idx" ON "need_events" USING btree ("need_id","at");--> statement-breakpoint
CREATE UNIQUE INDEX "need_subcategories_key" ON "need_subcategories" USING btree ("category_id","name");--> statement-breakpoint
CREATE UNIQUE INDEX "needs_one_open_per_beneficiary" ON "needs" USING btree ("beneficiary_id") WHERE "needs"."status" in ('new', 'review', 'processing');--> statement-breakpoint
CREATE INDEX "needs_beneficiary_idx" ON "needs" USING btree ("beneficiary_id");--> statement-breakpoint
CREATE INDEX "needs_routing_idx" ON "needs" USING btree ("status","city","category_id");--> statement-breakpoint
CREATE INDEX "notifications_user_idx" ON "notifications" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "phone_verifications_user_idx" ON "phone_verifications" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "places_name_gov_key" ON "places" USING btree ("name","governorate");--> statement-breakpoint
CREATE INDEX "places_governorate_idx" ON "places" USING btree ("governorate");--> statement-breakpoint
CREATE INDEX "sessions_user_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_key" ON "users" USING btree (lower("email"));