# إعداد قاعدة بيانات التطوير لمنصة احتياج.
#
# يُشغَّل مرة واحدة. ينشئ دور التطبيق وقاعدة البيانات، ثم يكتب DATABASE_URL
# و SESSION_SECRET في .env.local (مستثنى من git).
#
# كلمة مرور المستخدم postgres تُكتب في موجّه psql نفسه ولا تمرّ عبر هذا السكربت،
# وكلمة مرور دور التطبيق تُولَّد عشوائيًا هنا ولا يكتبها أحد.
#
#   powershell -ExecutionPolicy Bypass -File scripts\db-setup.ps1

$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$Role     = "ehtiyaj"
$Database = "ehtiyaj_dev"
$PgHost   = "localhost"
$PgPort   = 5432
$Super    = "postgres"

$root    = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root ".env.local"

# ---- إيجاد psql ----
$psql = $null
$candidate = Get-Command psql -ErrorAction SilentlyContinue
if ($candidate) {
  $psql = $candidate.Source
} else {
  $found = Get-ChildItem "C:\Program Files\PostgreSQL" -Directory -ErrorAction SilentlyContinue |
           Sort-Object Name -Descending |
           ForEach-Object { Join-Path $_.FullName "bin\psql.exe" } |
           Where-Object { Test-Path $_ } |
           Select-Object -First 1
  if ($found) { $psql = $found }
}
if (-not $psql) { throw "لم أجد psql. ثبّت PostgreSQL أو أضف مجلد bin إلى PATH." }

# ---- تأكيد قبل استبدال إعداد قائم ----
if (Test-Path $envFile) {
  if ((Get-Content $envFile -Raw) -match "DATABASE_URL") {
    Write-Host "ملف .env.local يحتوي DATABASE_URL بالفعل." -ForegroundColor Yellow
    $answer = Read-Host "هل أعيد ضبط الدور وقاعدة البيانات وأستبدل الملف؟ (y/N)"
    if ($answer -ne "y") { Write-Host "أُلغي الإعداد."; exit 0 }
  }
}

# ---- توليد أسرار عشوائية (متوافق مع Windows PowerShell 5.1) ----
function New-Secret([int]$Bytes) {
  $buffer = New-Object byte[] $Bytes
  $rng = [System.Security.Cryptography.RNGCryptoServiceProvider]::new()
  try { $rng.GetBytes($buffer) } finally { $rng.Dispose() }
  [Convert]::ToBase64String($buffer).Replace("+", "-").Replace("/", "_").Replace("=", "")
}

$AppPassword   = New-Secret 24
$SessionSecret = New-Secret 32
$escaped       = $AppPassword.Replace("'", "''")

# ---- إنشاء الدور وقاعدة البيانات ----
$sql = @"
DO `$`$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$Role') THEN
    ALTER ROLE $Role WITH LOGIN PASSWORD '$escaped';
  ELSE
    CREATE ROLE $Role WITH LOGIN PASSWORD '$escaped';
  END IF;
END
`$`$;

SELECT 'CREATE DATABASE $Database OWNER $Role ENCODING ''UTF8'' TEMPLATE template0'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$Database')
\gexec

GRANT ALL PRIVILEGES ON DATABASE $Database TO $Role;
"@

Write-Host ""
Write-Host "سيطلب psql الآن كلمة مرور المستخدم $Super — اكتبها في الموجّه." -ForegroundColor Cyan
Write-Host ""

$sql | & $psql -U $Super -h $PgHost -p $PgPort -d postgres -v ON_ERROR_STOP=1 -f -
if ($LASTEXITCODE -ne 0) { throw "فشل إنشاء الدور أو قاعدة البيانات." }

# ---- تجهيز القاعدة نفسها ----
$inner = @"
CREATE EXTENSION IF NOT EXISTS pgcrypto;
ALTER SCHEMA public OWNER TO $Role;
GRANT ALL ON SCHEMA public TO $Role;
"@

Write-Host "تجهيز القاعدة — كلمة مرور $Super مرة أخرى." -ForegroundColor Cyan
$inner | & $psql -U $Super -h $PgHost -p $PgPort -d $Database -v ON_ERROR_STOP=1 -f -
if ($LASTEXITCODE -ne 0) { throw "فشل تجهيز القاعدة." }

# ---- كتابة .env.local ----
$url = "postgresql://${Role}:${AppPassword}@${PgHost}:${PgPort}/${Database}"

$lines = @(
  "# Generated by scripts/db-setup.ps1 - not committed to git.",
  "DATABASE_URL=`"$url`"",
  "SESSION_SECRET=`"$SessionSecret`""
)

# ASCII عمدًا: علامة ترتيب البايتات تربك node --env-file
Set-Content -Path $envFile -Value $lines -Encoding ascii

Write-Host ""
Write-Host "تم. قاعدة البيانات: $Database — الدور: $Role" -ForegroundColor Green
Write-Host "كُتب DATABASE_URL و SESSION_SECRET في .env.local"
Write-Host ""
Write-Host "الخطوة التالية:  npm run db:push  ثم  npm run db:seed"
